Supports mannualy reset and OOP API.
macaron/go-mh-z19b pull request #4
Opened 2021-05-12 09:53 UTC by zeriyoshi

Add OOP API with Manually zero-point reset function.

Old API still supported, but doesn't have zero-point reset function.

2021-05-12 15:01 UTC, macaron requested changes
Nice contribute.Just a little bit more!
I wrote nitpick comments.
Thank you.

2021-05-12 15:01 UTC, macaron commented on cmd/mzh19b/main.go
> +		mhz19b.CalibrateDefault()
```suggestion
		_ = mhz19b.CalibrateDefault()
```

2021-05-12 15:01 UTC, macaron commented on README.md
> +    mhz16b := mhz19b.New("/dev/serial0")
What is mhz16b?

```suggestion
    mhz19b := mhz19b.New("/dev/serial0")
```

2021-05-12 15:01 UTC, macaron commented on README.md
> +    // mhz19b.CalibrateDefault()
👍

2021-05-12 15:01 UTC, macaron commented on cmd/mzh19b/main.go
> +	mhz19b "github.com/macaron/go-mh-z19b"
Why add a alias?
In many cases, Use this alias when import different packages of same name.

2021-05-12 15:01 UTC, macaron commented on cmd/mzh19b/main.go
> +	mhz19b := mhz19b.New(*device)
GoLand suggested "Variable 'mhz19b' collides with imported package name."
Uh...

golang user like very short variables.
```suggestion
	m := mhz19b.New(*device)
```

or

```suggestion
	co2 := mhz19b.New(*device)
```

2021-05-12 15:03 UTC, zeriyoshi commented on cmd/mzh19b/main.go
> +	mhz19b "github.com/macaron/go-mh-z19b"
This was automatically completed by VSCode's Go plugin

2021-05-13 16:53 UTC, macaron requested changes
Please fix variables 🙏

2021-05-13 16:53 UTC, macaron commented on cmd/mzh19b/main.go
> +		_ = mhz19b.CalibrateDefault()
```suggestion
		_ = m.CalibrateDefault()
```

2021-05-13 16:53 UTC, macaron commented on cmd/mzh19b/main.go
> +	ppm, _ := mhz19b.Read()
```suggestion
	ppm, _ := m.Read()
```

2021-05-14 13:13 UTC, merged